### ISSUE TITLE
Possible to manipulate .SUO when the associated .SLN is still loaded in VS?

### ISSUE THREAD

**Issue by UweKeim** [SimonCropp/SetStartupProjects#350]
#### Is the feature request related to a problem

I'm trying to manipulate a .SUO of an associated .SLN file that is loaded into an instance of Visual Studio 2022.

#### Describe the solution

I was trying your library from within a .NET Console application and discovered that it fails when the associated SLN is still loaded in another Visual Studio 2022 instance.

The error occurs within [`StartupProjectSuoCreator.CreateForSolutionFile` when it calls `File.Delete`](https://github.com/SimonCropp/SetStartupProjects/blob/main/src/SetStartupProjects/StartProjectSuoCreator.cs#L33) on an existing solution file:

> The process cannot access the file 'C:\MyProject\.vs\MyProject\v17\.suo' because it is being used by another process.

#### Describe alternatives considered

I would suggest to make the `StartupProjectSuoCreator.CreateForSolutionFile` work, even if the .SUO is loaded in another VS instance.

Personally, I do reckon that this will not be possible, but I want to suggest it anyway.

#### Additional context

I want to quickly my startup projects change on-the-fly. First closing VS, then calling your library and finally opening VS again would take much longer than doing the switching of the startup projects it through the UI.

Maybe there is a way to achieve my goal. 

(In any case: Thank you very much for the efforts you put into this library 🙂)

**Comment by SimonCropp** [comment]
yeah i dont think there is anything i can do about a locked file :(
