### ISSUE TITLE
[question] How can I use it with my solution?

### ISSUE THREAD

**Issue by igorushi** [SimonCropp/SetStartupProjects#55]
I'm trying to understand how to integrate this nuget in my solution. From the example I understand that it requires to create some side project that manipulates my solution. Generally I'm looking to save some how multiple startup projects  settings to version control and I can't get how this can be done with "SetStartupProjects". Can you please assist?

**Comment by SimonCropp** [comment]
not a scenario i have ever required. the simplest approach i can think of is 

 * add a config file that stores what the startup projects should be
 * check that file in to source control
 * create a command line version of SetStartupProjects that respects the config file
 * run the command line on source control events, eg git hooks https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

can u think of a better approach?
